spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym
    username: root
    password: qwerty@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
        ddl-auto: update
server:
  port: 8083
