server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: vivek#qwer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true